game_name: post-apocalyptic-short
genre: "post-apocalyptic, mystery, dark fantasy, sci-fi"
language: "English"
lore_seed: "Attempt of building an utopia turns the world into a dystopian one"
stats:
  - health
  - attack
  - defense
  - magic power
npcs: 2
items: 4
story_size: 512
models:
  lore_generator: 
    provider: openai
    create_params:
      model: gpt-5
      reasoning_effort: medium
      verbosity: medium
  narrator: 
    provider: openai
    create_params:
      model: gpt-5-mini
      reasoning_effort: low
      verbosity: low
  summarizer:
    provider: openai
    create_params:
      model: gpt-5-mini
      reasoning_effort: medium
      verbosity: medium
